# Generated by Django 5.1.2 on 2024-11-01 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_display', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('population', models.BigIntegerField()),
                ('class_size', models.BigIntegerField()),
                ('location', models.CharField(max_length=255)),
                ('atmosphere', models.CharField(max_length=255)),
                ('crime_rate', models.CharField(max_length=255)),
                ('faith_life', models.CharField(max_length=255)),
                ('slug', models.SlugField(default='')),
                ('activities', models.ManyToManyField(blank=True, related_name='schools_activities', to='college_display.activity')),
                ('majors', models.ManyToManyField(blank=True, related_name='schools_majors', to='college_display.major')),
                ('price_range', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_ranges', to='college_display.pricerange')),
            ],
        ),
    ]
