# Generated by Django 5.1.2 on 2024-11-01 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_display', '0002_college'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='category',
            field=models.CharField(default='Miscellaneous', max_length=255),
        ),
    ]
