# Generated by Django 5.1.2 on 2024-11-01 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_display', '0003_activity_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
