# Generated by Django 5.1.2 on 2024-11-02 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_display', '0006_remove_college_location_college_city_college_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='atmosphere',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='college',
            name='class_size',
            field=models.BigIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='crime_rate',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='college',
            name='faith_life',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
