# Generated by Django 5.1.2 on 2024-11-02 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_display', '0007_alter_college_atmosphere_alter_college_class_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='price',
            field=models.IntegerField(blank=True, max_length=255),
        ),
    ]
