# Generated by Django 5.1.2 on 2024-11-02 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_display', '0008_alter_college_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='price',
            field=models.IntegerField(blank=True),
        ),
    ]
